name: Build Android Release APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Install dependencies
        run: npm install --workspaces
        
      - name: Build client
        run: npm run build --workspace client
        env:
          VITE_SERVER_URL: ${{ vars.PRODUCTION_SERVER_URL }}
          VITE_ADMOB_BANNER_LOBBY: ${{ vars.VITE_ADMOB_BANNER_LOBBY }}
          VITE_ADMOB_BANNER_POSTGAME: ${{ vars.VITE_ADMOB_BANNER_POSTGAME }}
        
      - name: Add Android platform
        working-directory: client
        run: npx cap add android
        
      - name: Generate icons
        working-directory: client
        run: npx capacitor-assets generate --android
        
      - name: Sync Capacitor
        working-directory: client
        run: npx cap sync android
        
      - name: Add signing config to build.gradle
        working-directory: client/android/app
        run: |
          sed -i '/android {/a \
              signingConfigs { \
                  release { \
                      storeFile file(System.getenv("KEYSTORE_FILE") ?: "release.keystore") \
                      storePassword System.getenv("KEYSTORE_PASSWORD") \
                      keyAlias System.getenv("KEY_ALIAS") \
                      keyPassword System.getenv("KEY_PASSWORD") \
                  } \
              }' build.gradle

          sed -i '/buildTypes {/!b;n;c\        release {\n            signingConfig signingConfigs.release' build.gradle

      - name: Make gradlew executable
        working-directory: client/android
        run: chmod +x gradlew
        
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > client/android/app/release.keystore
        
      - name: Build Release APK
        working-directory: client/android
        run: ./gradlew assembleRelease --stacktrace
        env:
          KEYSTORE_FILE: release.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          
      - name: List build outputs
        if: always()
        run: find client/android/app/build/outputs -type f
        
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: client/android/app/build/outputs/apk/**/*.apk
          
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: client/android/app/build/outputs/apk/**/*.apk
